### ISSUE TITLE
not be able to build on rocm 1.7.x 

### ISSUE THREAD

**Issue by tingxingdong** [ROCmSoftwarePlatform/rocRAND#13]
building error  on Vega10 is like 

In file included from /home/rocRAND/library/src/rocrand.cpp:23:
In file included from /home/rocRAND/library/src/rng/generators.hpp:27:
/home/rocRAND/library/src/rng/sobol32.hpp:159:9: error: no matching function for call to 'hipLaunchKernelGGL'
        hipLaunchKernelGGL(
        ^~~~~~~~~~~~~~~~~~
/home/rocRAND/library/src/rng/sobol32.hpp:186:16: note: in instantiation of function template specialization
      'rocrand_sobol32::generate<double, normal_distribution<double> >' requested here
        return generate(data, data_size, distribution);

=======================================
[master u=] $ uname -a 
Linux tim-hsa 4.16.0-rc1-kfd-compute-roc-master-7620 #1 SMP Mon Mar 5 13:33:13 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

[master u=] $ ccmake ../
 AMDGPU_TARGETS                   gfx803;gfx900                                                                                                                                            
 BUILD_BENCHMARK                  OFF                                                                                                                                                      
 BUILD_CRUSH_TEST                 OFF                                                                                                                                                      
 BUILD_FORTRAN_WRAPPER            OFF                                                                                                                                                      
 BUILD_SHARED_LIBS                ON                                                                                                                                                       
 BUILD_TEST                       OFF                                                                                                                                                      
 CMAKE_BUILD_TYPE                 Release                                                                                                                                                  
 CMAKE_INSTALL_PREFIX             /opt/rocm                                                                                                                                                
 CMAKE_INSTALL_RPATH_USE_LINK_P   TRUE                                                                                                                                                     
 DPKG_EXE                         /usr/bin/dpkg                                                                                                                                            
 ENABLE_INLINE_ASM                ON                                                                                                                                                       
 HIP_ROOT_DIR                     /opt/rocm/hip                                                                                                                                            
 HSA_HEADER                       /opt/rocm/include                                                                                                                                        
 HSA_LIBRARY                      /opt/rocm/lib/libhsa-runtime64.so                                                                                                                        
 RPMBUILD_EXE                     RPMBUILD_EXE-NOTFOUND                                                                                                                                    
 UNWIND_LIBRARY                   /usr/lib/x86_64-linux-gnu/libunwind.so                                                                                                                   
 hcc_DIR                          /opt/rocm/hcc/lib/cmake/hcc                                                                                                                              
 hip_DIR                          /opt/rocm/hip/lib/cmake/hip

**Comment by jszuppe** [comment]
Which branch?

**Comment by bragadeesh** [comment]
@tingxingdong can you use the rocm_1_7_1 branch

**Comment by tingxingdong** [comment]
master branch. 
I build both on rocm 1.7.1 and rocm master. both failed with the same error.

**Comment by sunway513** [comment]
@tingxingdong , try test_roc_master  branch. It looks like the master branch doesn't have change for HIP-246PR.

**Comment by tingxingdong** [comment]
I must build it for rocm 1.7.1, it is for CentOS rpm release.

**Comment by VincentSC** [comment]
Could one of you make a PR for that HIP-246PR?

**Comment by sunway513** [comment]
@bragadeesh , please help review and merge all the required changes to work for HIP-246PR. Those changes were mainly to add some static cast in hipLaunchKernelGGL call, such as:
https://github.com/ROCmSoftwarePlatform/rocRAND/commit/527c8f39fd315b2604c56e1b4ac1747b3cc4b105
